In [1]:
import torch

In [23]:
#Creat tensor
tensor = torch.rand(4,5)

In [8]:
#Show
tensor

tensor([[-1.3991, -1.3593, -1.7936, -1.3701, -1.4981],
        [-1.2056, -1.7252, -1.6969, -1.2919, -1.1024],
        [-1.8998, -1.9488, -1.1077, -1.1085, -1.9987],
        [-1.5688, -1.0782, -1.5648, -1.0120, -1.4180]])

In [4]:
#Info
print(tensor)
print(f"shape : {tensor.shape}")
print(f"datatype : {tensor.dtype}")
print(f"device : {tensor.device}")

tensor([[0.6009, 0.6407, 0.2064, 0.6299, 0.5019],
        [0.7944, 0.2748, 0.3031, 0.7081, 0.8976],
        [0.1002, 0.0512, 0.8923, 0.8915, 0.0013],
        [0.4312, 0.9218, 0.4352, 0.9880, 0.5820]])
shape : torch.Size([4, 5])
datatype : torch.float32
device : cpu


In [9]:
#Addition with numbers
tensorr = tensor + 12
tensor

tensor([[-1.3991, -1.3593, -1.7936, -1.3701, -1.4981],
        [-1.2056, -1.7252, -1.6969, -1.2919, -1.1024],
        [-1.8998, -1.9488, -1.1077, -1.1085, -1.9987],
        [-1.5688, -1.0782, -1.5648, -1.0120, -1.4180]])

In [10]:
#Divide by number
tensor = tensor - 2
tensor

tensor([[-3.3991, -3.3593, -3.7936, -3.3701, -3.4981],
        [-3.2056, -3.7252, -3.6969, -3.2919, -3.1024],
        [-3.8998, -3.9488, -3.1077, -3.1085, -3.9987],
        [-3.5688, -3.0782, -3.5648, -3.0120, -3.4180]])

In [11]:
#Multiply by number
tensor * 3

tensor([[-10.1974, -10.0780, -11.3807, -10.1104, -10.4944],
        [ -9.6169, -11.1756, -11.0907,  -9.8758,  -9.3073],
        [-11.6995, -11.8465,  -9.3232,  -9.3254, -11.9961],
        [-10.7064,  -9.2346, -10.6944,  -9.0360, -10.2539]])

In [12]:
#Multiply by number
torch.multiply(tensor ,3)

tensor([[-10.1974, -10.0780, -11.3807, -10.1104, -10.4944],
        [ -9.6169, -11.1756, -11.0907,  -9.8758,  -9.3073],
        [-11.6995, -11.8465,  -9.3232,  -9.3254, -11.9961],
        [-10.7064,  -9.2346, -10.6944,  -9.0360, -10.2539]])

In [13]:
torch.add(tensor,2)

tensor([[-1.3991, -1.3593, -1.7936, -1.3701, -1.4981],
        [-1.2056, -1.7252, -1.6969, -1.2919, -1.1024],
        [-1.8998, -1.9488, -1.1077, -1.1085, -1.9987],
        [-1.5688, -1.0782, -1.5648, -1.0120, -1.4180]])

In [19]:
tensor_1 =torch.rand(3,2)
tensor_2 = torch.rand(2,4)

In [21]:
#Multiply by tensor
torch.matmul(tensor_1,tensor_2)

tensor([[0.2942, 0.2039, 0.3863, 0.1335],
        [0.7244, 0.5582, 0.8638, 0.3078],
        [0.5814, 0.4055, 0.7598, 0.2630]])

In [34]:
torch.mm(tensor_1 , tensor_2)

tensor([[0.2942, 0.2039, 0.3863, 0.1335],
        [0.7244, 0.5582, 0.8638, 0.3078],
        [0.5814, 0.4055, 0.7598, 0.2630]])

In [33]:
tensor_1 @ tensor_2

tensor([[0.2942, 0.2039, 0.3863, 0.1335],
        [0.7244, 0.5582, 0.8638, 0.3078],
        [0.5814, 0.4055, 0.7598, 0.2630]])

In [24]:
#Creat tensor
x = torch.rand(2,3)

In [26]:
x

tensor([[0.3368, 0.2526, 0.9023],
        [0.2512, 0.5753, 0.4237]])

In [25]:
# x is tensor, 0 is first dimention, 1 is second dimention

torch.transpose(x,0,1)

tensor([[0.3368, 0.2512],
        [0.2526, 0.5753],
        [0.9023, 0.4237]])

In [27]:
x.T

tensor([[0.3368, 0.2512],
        [0.2526, 0.5753],
        [0.9023, 0.4237]])

In [28]:
torch.t(x)

tensor([[0.3368, 0.2512],
        [0.2526, 0.5753],
        [0.9023, 0.4237]])

In [31]:
#Creat tensors
tensor_3 = torch.rand(2,5)
tensor_4 = torch.rand(2,4)

In [32]:
tensor_3.T @ tensor_4

tensor([[0.8450, 0.6724, 0.1911, 0.7099],
        [0.3629, 0.7531, 0.3252, 0.3232],
        [1.0977, 1.0764, 0.3544, 0.9302],
        [1.0302, 0.9224, 0.2867, 0.8695],
        [0.3186, 0.3331, 0.1137, 0.2708]])