In [40]:
import torch

In [41]:
#Creat tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [42]:
y = torch.arange(0,100. , 4) #(0, 100, 4, dtype=torch.float32)
y

tensor([ 0.,  4.,  8., 12., 16., 20., 24., 28., 32., 36., 40., 44., 48., 52.,
        56., 60., 64., 68., 72., 76., 80., 84., 88., 92., 96.])

In [43]:
#return max
x.max

<function Tensor.max>

In [44]:
#return min
x.min

<function Tensor.min>

In [45]:
#Convert to float
x_float = x.type(torch.DoubleTensor)

In [46]:
x_float.dtype

torch.float64

In [47]:
#To calculate the average, we need a decimal tensor
x_float.mean()

tensor(45., dtype=torch.float64)

In [48]:
#sum items
x.sum()

tensor(450)

## Index

In [49]:
torch.argmax(x)

tensor(9)

In [50]:
x[0] = 1000

In [51]:
x

tensor([1000,   10,   20,   30,   40,   50,   60,   70,   80,   90])

In [52]:
torch.argmin(x)

tensor(1)

## Tensor Datatype

In [53]:
x.dtype

torch.int64

In [54]:
x_float.dtype

torch.float64

In [55]:
y.dtype

torch.float32

In [56]:
y_64 = y.type(torch.float64)

In [57]:
y_64.dtype

torch.float64

## Reshape

In [58]:
a = torch.arange(1,9.)
a

tensor([1., 2., 3., 4., 5., 6., 7., 8.])

In [59]:
a, a.shape, a.dtype

(tensor([1., 2., 3., 4., 5., 6., 7., 8.]), torch.Size([8]), torch.float32)

In [60]:
a.ndim

1

In [61]:
b = a.reshape(1,8)

In [62]:
b, b.shape, b.dtype

(tensor([[1., 2., 3., 4., 5., 6., 7., 8.]]), torch.Size([1, 8]), torch.float32)

In [63]:
b.ndim

2

In [64]:
c = a.reshape(2,4)

In [65]:
c , c.shape

(tensor([[1., 2., 3., 4.],
         [5., 6., 7., 8.]]),
 torch.Size([2, 4]))

In [66]:
d = a.reshape(4,2)
d

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])

### View

In [67]:
#Show View of a. It refers to the previous one
v = a.view(2,4)
v , a

(tensor([[1., 2., 3., 4.],
         [5., 6., 7., 8.]]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8.]))

In [68]:
v[0][0] = 111

In [69]:
v , a

(tensor([[111.,   2.,   3.,   4.],
         [  5.,   6.,   7.,   8.]]),
 tensor([111.,   2.,   3.,   4.,   5.,   6.,   7.,   8.]))

### Stack

In [70]:
a

tensor([111.,   2.,   3.,   4.,   5.,   6.,   7.,   8.])

In [71]:
a_stack = torch.stack([a,a],dim=0)
a_stack

tensor([[111.,   2.,   3.,   4.,   5.,   6.,   7.,   8.],
        [111.,   2.,   3.,   4.,   5.,   6.,   7.,   8.]])

In [72]:
a_stack_1 = torch.stack([a,a],dim=1)
a_stack_1

tensor([[111., 111.],
        [  2.,   2.],
        [  3.,   3.],
        [  4.,   4.],
        [  5.,   5.],
        [  6.,   6.],
        [  7.,   7.],
        [  8.,   8.]])

### Squeeze()

In [73]:
a

tensor([111.,   2.,   3.,   4.,   5.,   6.,   7.,   8.])

In [74]:
a.shape

torch.Size([8])

In [75]:
a_1_8 = a.reshape(1,8)
a_1_8

tensor([[111.,   2.,   3.,   4.,   5.,   6.,   7.,   8.]])

In [76]:
a_1_8.shape

torch.Size([1, 8])

In [77]:
a_1_8_sq = a_1_8.squeeze()
a_1_8_sq

tensor([111.,   2.,   3.,   4.,   5.,   6.,   7.,   8.])

In [78]:
a_1_8_sq.shape

torch.Size([8])

In [79]:
a_1_8_sq.unsqueeze(dim=0)

tensor([[111.,   2.,   3.,   4.,   5.,   6.,   7.,   8.]])

## Permute()

In [80]:
img = torch.rand(size=(255,255,3))

In [81]:
img

tensor([[[0.0598, 0.1367, 0.9723],
         [0.8049, 0.9248, 0.3121],
         [0.4958, 0.2514, 0.5078],
         ...,
         [0.8832, 0.1737, 0.5878],
         [0.0616, 0.6424, 0.0791],
         [0.5117, 0.5932, 0.2864]],

        [[0.9079, 0.3099, 0.0579],
         [0.8943, 0.3599, 0.7707],
         [0.6478, 0.2989, 0.4373],
         ...,
         [0.4274, 0.4560, 0.1561],
         [0.4347, 0.6359, 0.8210],
         [0.3954, 0.0282, 0.1253]],

        [[0.4552, 0.4543, 0.7374],
         [0.1499, 0.2253, 0.1623],
         [0.9785, 0.3544, 0.1689],
         ...,
         [0.7293, 0.1929, 0.4569],
         [0.9973, 0.8046, 0.8710],
         [0.4938, 0.1622, 0.9257]],

        ...,

        [[0.0762, 0.5959, 0.3099],
         [0.5750, 0.2153, 0.5490],
         [0.4687, 0.1215, 0.9505],
         ...,
         [0.0618, 0.0161, 0.8776],
         [0.3806, 0.2615, 0.4981],
         [0.7421, 0.4825, 0.3783]],

        [[0.3574, 0.3521, 0.2877],
         [0.4623, 0.8142, 0.7512],
         [0.

In [82]:
#displacement
img.permute(2,0,1)

tensor([[[0.0598, 0.8049, 0.4958,  ..., 0.8832, 0.0616, 0.5117],
         [0.9079, 0.8943, 0.6478,  ..., 0.4274, 0.4347, 0.3954],
         [0.4552, 0.1499, 0.9785,  ..., 0.7293, 0.9973, 0.4938],
         ...,
         [0.0762, 0.5750, 0.4687,  ..., 0.0618, 0.3806, 0.7421],
         [0.3574, 0.4623, 0.3026,  ..., 0.8441, 0.1564, 0.1860],
         [0.1166, 0.6619, 0.0708,  ..., 0.6560, 0.9895, 0.7437]],

        [[0.1367, 0.9248, 0.2514,  ..., 0.1737, 0.6424, 0.5932],
         [0.3099, 0.3599, 0.2989,  ..., 0.4560, 0.6359, 0.0282],
         [0.4543, 0.2253, 0.3544,  ..., 0.1929, 0.8046, 0.1622],
         ...,
         [0.5959, 0.2153, 0.1215,  ..., 0.0161, 0.2615, 0.4825],
         [0.3521, 0.8142, 0.1585,  ..., 0.2528, 0.2237, 0.3077],
         [0.3099, 0.8658, 0.4086,  ..., 0.3271, 0.6652, 0.8311]],

        [[0.9723, 0.3121, 0.5078,  ..., 0.5878, 0.0791, 0.2864],
         [0.0579, 0.7707, 0.4373,  ..., 0.1561, 0.8210, 0.1253],
         [0.7374, 0.1623, 0.1689,  ..., 0.4569, 0.8710, 0.

## Select

In [84]:
x

tensor([1000,   10,   20,   30,   40,   50,   60,   70,   80,   90])

In [83]:
x[4]

tensor(40)

In [85]:
xx = x.reshape(2,5)

In [86]:
xx

tensor([[1000,   10,   20,   30,   40],
        [  50,   60,   70,   80,   90]])

In [87]:
xx[0]

tensor(1000)

In [90]:
xx[0,1]

tensor(10)

In [89]:
xx[:]

tensor([[1000,   10,   20,   30,   40],
        [  50,   60,   70,   80,   90]])

In [91]:
xx[:,0]

tensor([1000,   50])

In [92]:
xx[:1]

tensor([[1000,   10,   20,   30,   40]])